### ISSUE TITLE
Next ISO batch TODO

### ISSUE THREAD

**Issue by q66** [void-ppc/void-mklive#4]
This issue will stay open and track the current issues to deal with before spinning the next set of ISO images.

Feel free to bring up any other issues that might be worth dealing with.

# Upcoming set

- [ ] ZFS support

# Done (included in 20200411)

- [x] ATi Rage 128 and older support in 32-bit images (https://github.com/void-ppc/void-packages/issues/31)
- [x] serial console enablement in live (`ttyS0`/`hvc0`/`hvsi0`: https://github.com/void-ppc/void-packages/issues/30)
- [x] ~~Epiphany browser missing icons~~ will be worked around in the iso maker instead (https://github.com/void-ppc/void-packages/issues/32)
- [x] possibly offer `yaboot` as an alternative bootloader for live images
- [x] provide an alternative kernel option (4.4) on big endian (for old machines where modern kernels tend to be troublesome)
- [x] ~~test and fix all desktops for graphical flavor images that can be created on all archs~~ only Xfce will be provided as a graphical flavor for live images next time; people wanting other desktops will be able to install their own separately (reason: takes too long to generate, too much space, too much effort testing every one of them)

# Backlog
